[package]
name = "rabbitmq"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "1.6.0"
tokio = { version = "1.32", features = ["full"] }
actix-web =   "4.5.1"
futures = "0.3.25"
image = "0.25.1"
log = { version = "0.4", features = ["std", "serde"] }